# latexindent.pl 設定ファイル
# https://latexindentpl.readthedocs.io/
#

# ------------------------------------------------------------------
# 基本設定
# ------------------------------------------------------------------
# デフォルトのインデントを4スペースに設定
defaultIndent: "    "
# プリアンブル（\documentclass ~ \begin{document}）をインデントする
indentPreamble: 1
# 行末の不要な空白を自動で削除する
removeTrailingWhitespace:
  beforeProcessing: 1
  afterProcessing: 1
# 独立した行にあるコメントを、周囲のコードと同じレベルにインデントする
indentFirstLineComments: 1

# ------------------------------------------------------------------
# 改行の調整 (バージョン管理との親和性向上)
# ------------------------------------------------------------------
modifyLineBreaks:
  # 環境（\begin{} ... \end{}）の開始・終了を独立した行にする
  environments:
    BeginStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
  # 2行以上の連続する空行を、1行の空行にまとめる
  condenseMultipleBlankLinesInto: 1

# ------------------------------------------------------------------
# インデントの微調整
# ------------------------------------------------------------------
# document環境はインデントしない
indentRules:
  document: "0"

# item環境のインデントを調整
indentAfterItems:
  item: 1
  itemize: 1
  enumerate: 1

# 日本語対応：特定のコマンド内で追加のインデントを行わない
noAdditionalIndent:
  textbf: 0
  textit: 0
  emph: 0
  underline: 0
  pbox: 0
  mbox: 0
  textgt: 0 # ゴシック体
  textmc: 0 # 明朝体

# ------------------------------------------------------------------
# オプション引数の整形
# ------------------------------------------------------------------
# \documentclass[...]等のオプション引数をキー=値のペアごとに改行して整形する
optionalArgumentIndentation:
  commandNames:
    - includegraphics
    - usepackage
    - documentclass
    - input
    - lstinputlisting
    - href
  breakAfterComma: 1
  indentAfterOpenBracket: 1

# ------------------------------------------------------------------
# 数式・表のアライメント設定
# ------------------------------------------------------------------
lookForAlignDelims:
  align: 1
  align*: 1
  alignat: 1
  array: 1
  tabular: 1
  matrix: 1
  pmatrix: 1
  bmatrix: 1
  vmatrix: 1
  cases: 1
  split: 1

alignDelims:
  spacesBeforeAmpersand: 1
  spacesAfterAmpersand: 1
  spacesBeforeDoubleBackSlash: 1
  justification: center

# ------------------------------------------------------------------
# 置換設定 (リスト整形)
# ------------------------------------------------------------------
substitutions:
  # item間の空行を削除するルール
  items:
    s: '(\\item(?:\[.*?\])?\s*(?:\n\s*){2,})\s*(?=\\item)'
    r: "$1"

# ------------------------------------------------------------------
# 文字置換設定
# ------------------------------------------------------------------
replacements:
  - this: "、"
    that: "，"
  - this: "。"
    that: "．"

# ------------------------------------------------------------------
# 特殊な環境の定義
# ------------------------------------------------------------------
specialBeginEnd:
  displayMath:
    begin: '\\\['
    end: '\\\]'
    lookForThis: 1
  inlineMath:
    begin: '\\\('
    end: '\\\)'
    lookForThis: 1

# ------------------------------------------------------------------
# バックアップ設定
# ------------------------------------------------------------------
# 複数世代のバックアップは作成しない
cycleThroughBackUps: 0
backupExtension: .bak
